title: Lumiryx Portfolio
description: Developer Portfolio
baseurl: ""
url: "https://lumiryx.github.io"

markdown: kramdown
permalink: pretty
theme: jekyll-theme-so-simple

collections:
  projects:
    output: true
    permalink: /projects/:name/
  tools:
    output: true
    permalink: /tools/:name/
  writeups:
    output: true
    permalink: /writeups/:name/